# Site configuration
title: "Shengze Ding"
description: "Academic personal website - Research in Scientific Machine Learning"
url: "https://shengzeding.github.io"
baseurl: ""
locale: "en-US"

# Site Author
author:
  name: "Shengze Ding"
  avatar: "my-avatar.jpg"
  bio: "Research Assistant @ND<br>Undergrad @SJTU"
  location: "Shanghai, China"
  email: "shengzeding@sjtu.edu.cn"
  linkedin: "shengze-ding"
  instagram: "shengze_ding"
  github: "shengzeding"

# Build settings
markdown: kramdown
remote_theme: academicpages/academicpages.github.io
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfile
  - gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
